const moviesDB = {
    inception : {
        title :"Inception",
        year :"2010",
        rated:"PG-13",
        released:"16 Jul 2010",
        runtime:"148 min",
        genre:"Action, Adventure, Sci-Fi, Thriller",
        director:"Christopher Nolan",
        writer:"Christopher Nolan",
        actors:"Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
        plot:"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        language:"English, Japanese, French",
        country:"USA, UK","Awards":"Won 4 Oscars. Another 153 wins & 220 nominations.",
        poster:"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
        rating:"8.8"
    },
    aQuietPlace : {
        title:"A Quiet Place",
        year:"2018",
        rated:"PG-13",
        released:"06 Apr 2018",
        runtime:"90 min",
        genre:"Drama,Horror, Sci-Fi",
        director:"John Krasinski",
        writer:"Bryan Woods, Scott Beck, John Krasinski",
        actors:"Emily Blunt, John Krasinski, Millicent Simmonds",
        plot:"In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
        language:"American Sign , English",
        country:"United States",
        awards:"Nominated for 1 Oscar. 34 wins & 115 nominations total",
        poster:"https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_SX300.jpg",
        rating : "7.5"
    },
    extraction : {
        title:"Extraction",
        year:"2020",
        released:"24 Apr 2020",
        runtime:"116 min",
        genre:"Action, Thriller",
        director:"Sam Hargrave",
        writer:"Joe Russo, Ande Parks, Anthony Russo",
        actors:"Chris Hemsworth, Bryon Lerum, Ryder Lerum, Randeep Hooda, Priyanshu Painyuli",
        plot:"Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he's enlisted to rescue the kidnapped son of an imprisoned international crime lord.",
        language:"English, Hindi, Bengali",
        country:"United States, Canada, Thailand",
        poster:"https://m.media-amazon.com/images/M/MV5BMDJiNzUwYzEtNmQ2Yy00NWE4LWEwNzctM2M0MjE0OGUxZTA3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        rating:"6.7"
    },
    moneyball : {
        title:"Moneyball",
        year:"2011",
        released:"23 Sep 2011",
        runtime:"133 min",
        genre:"Biography, Drama, Sport",
        director:"Bennett Miller",
        writer:"Steven Zaillian (screenplay), Aaron Sorkin (screenplay), Stan Chervin (story), Michael Lewis (book)",
        actors:"Brad Pitt, Jonah Hill, Philip Seymour Hoffman, Robin Wright",
        plot:"Oakland A's general manager Billy Beane's successful attempt to assemble a baseball team on a lean budget by employing computer-generated analysis to acquire new players.",
        language:"English",
        country:"USA",
        poster:"https://m.media-amazon.com/images/M/MV5BMjAxOTU3Mzc1M15BMl5BanBnXkFtZTcwMzk1ODUzNg@@._V1_SX300.jpg",
        rating:"7.6"
    },
    hotelMumbai : {
        title:"Hotel Mumbai",
        year:"2018",
        released:"29 Mar 2019",
        runtime:"123 min",
        genre:"Action, Drama, History, Thriller",
        director:"Anthony Maras",
        writer:"John Collee, Anthony Maras",
        actors:"Dev Patel, Armie Hammer, Amandeep Singh, Anupam Kher, Suhail Nayyar, Nazanin Biniadi, Dinesh Kumar",
        plot:"The true story of the Taj Hotel terrorist attack in Mumbai. Hotel staff risk their lives to keep everyone safe as people make unthinkable sacrifices to protect themselves and their families.",
        language:"Hindi, English, Punjabi",
        country:"Australia, USA, UK, India, Singapore",
        poster:"https://m.media-amazon.com/images/M/MV5BYTJlZWY2YjYtZGIxMy00MDEwLTliNzMtZGM3MDQ1NzlmNDY1XkEyXkFqcGdeQXVyNDY2MjcyOTQ@._V1_SX300.jpg",
        rating:"7.6"
    },
    theMatrix : {
        title:"The Matrix",
        year:"1999",
        released:"31 Mar 1999",
        runtime:"136 min",
        genre:"Action, Sci-Fi",
        director:"Lana Wachowski, Lilly Wachowski",
        writer:"Lilly Wachowski, Lana Wachowski",
        actors:"Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        plot:"When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        language:"English",
        country:"United States, Australia",
        poster:"https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        rating:"8.7"
    },
    seven : {
        title:"Se7en",
        year:"1995",
        released:"22 Sep 1995",
        runtime:"127 min",
        genre:"Crime, Drama, Mystery",
        director:"David Fincher",
        writer:"Andrew Kevin Walker",
        actors:"Morgan Freeman, Brad Pitt, Kevin Spacey",
        plot:"Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        language:"English",
        country:"United States",
        poster:"https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        rating:"8.6"
    },
    goneGirl : {
        title:"Gone Girl",
        year:"2014",
        released:"03 Oct 2014",
        runtime:"149 min",
        genre:"Drama, Mystery, Thriller",
        director:"David Fincher",
        writer:"Gillian Flynn (screenplay), Gillian Flynn (novel)",
        actors:"Ben Affleck, Rosamund Pike, Neil Patrick Harris, Tyler Perry",
        plot:"With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
        language:"English",
        country:"USA",
        poster:"https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_SX300.jpg",
        rating:"8.1"
    },
    sicario : {
        title:"Sicario",
        year:"2015",
        released:"02 Oct 2015",
        runtime:"121 min",
        genre:"Action, Crime, Drama",
        director:"Denis Villeneuve",
        writer:"Taylor Sheridan",
        actors:"Emily Blunt, Josh Brolin, Benicio Del Toro",
        plot:"An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.",
        language:"English, Spanish",
        country:"United States, Mexico, Hong Kong" ,
        poster:"https://m.media-amazon.com/images/M/MV5BMjA5NjM3NTk1M15BMl5BanBnXkFtZTgwMzg1MzU2NjE@._V1_SX300.jpg",
        rating:"7.6"
    },

    blackPanther : {
        title:"Black Panther",
        year:"2018",
        rated:"PG-13",
        released:"16 Feb 2018",
        runtime:"134 min",
        genre:"Action, Adventure, Sci-Fi",
        director:"Ryan Coogler",
        writer:"Ryan Coogler, Joe Robert Cole, Stan Lee (based on the Marvel comics), Jack Kirby (based on the Marvel Comics)",
        actors:"Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
        plot:"T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
        language:"English, Swahili, Nama, Xhosa, Korean",
        country:"USA, South Africa",
        poster:"https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg",
        rating:"7.3"
    },
    argo : {
        title:"Argo",
        year:"2012",
        released:"12 Oct 2012",
        runtime:"120 min",
        genre:"Biography, Drama, Thriller",
        director:"Ben Affleck",
        writer:"Chris Terrio (screenplay by), Tony Mendez (based on a selection from \"The Master of Disguise\" by), Joshuah Bearman (based on the Wired Magazine article \"The Great Escape\" by)",
        actors:"Ben Affleck, Bryan Cranston, Alan Arkin, John Goodman",
        plot:"Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1979.",
        language:"English, Persian, German, Arabic",
        country:"USA, UK",
        poster:"https://m.media-amazon.com/images/M/MV5BNzljNjY3MDYtYzc0Ni00YjU0LWIyNDUtNTE0ZDRiMGExMjZlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        rating:"7.7"
    },
    prisoners : {
        title:"Prisoners",
        year:"2013",
        released:"20 Sep 2013",
        runtime:"153 min",
        genre:"Crime, Drama, Mystery, Thriller",
        director:"Denis Villeneuve",
        writer:"Aaron Guzikowski",
        actors:"Hugh Jackman, Jake Gyllenhaal, Viola Davis, Maria Bello",
        plot:"When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.",
        language:"English",
        country:"USA",
        awards:"Nominated for 1 Oscar. Another 10 wins & 37 nominations.",
        poster:"https://m.media-amazon.com/images/M/MV5BMTg0NTIzMjQ1NV5BMl5BanBnXkFtZTcwNDc3MzM5OQ@@._V1_SX300.jpg",
        rating:"8.1"
    },
    nightcrawler : {
        title:"Nightcrawler",
        year:"2014",
        released:"31 Oct 2014",
        runtime:"117 min",
        genre:"Crime, Drama, Thriller",
        director:"Dan Gilroy",
        writer:"Dan Gilroy",
        actors:"Jake Gyllenhaal, Riz Ahmed, Marco Rodríguez, Bill Paxton",
        plot:"When Louis Bloom, a con man desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant to become the star of his own story.",
        language:"English",
        country:"USA",
        poster:"https://m.media-amazon.com/images/M/MV5BN2U1YzdhYWMtZWUzMi00OWI1LWFkM2ItNWVjM2YxMGQ2MmNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        rating:"7.8"
    },
    interstellar : {
        title:"Interstellar",
        year:"2014",
        rated:"PG-13",
        released:"07 Nov 2014",
        runtime:"169 min",
        genre:"Adventure, Drama, Sci-Fi",
        director:"Christopher Nolan",
        writer:"Jonathan Nolan, Christopher Nolan",
        actors:"Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
        plot:"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        language:"English",
        country:"USA, UK, Canada",
        poster:"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        rating:"8.6"
    },
    goodfellas: {
        title:"Goodfellas",
        year:"1990",
        released:"21 Sep 1990",
        runtime:"146 min",genre:"Biography, Crime, Drama",
        director:"Martin Scorsese",
        writer:"Nicholas Pileggi (book), Nicholas Pileggi (screenplay), Martin Scorsese (screenplay)",
        actors:"Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco",
        plot:"The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
        language:"English, Italian",
        country:"USA",
        poster:"https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        rating:"8.7"
    },
    shutterIsland : {
        title:"Shutter Island",
        year:"2010",
        released:"19 Feb 2010",
        runtime:"138 min",
        genre:"Mystery, Thriller",
        director:"Martin Scorsese",
        writer:"Laeta Kalogridis, Dennis Lehane",
        actors:"Leonardo DiCaprio, Emily Mortimer, Mark Ruffalo, Ben Kingsley",
        plot:"In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
        language:"English, German",
        country:"United States",
        poster:"https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        rating:"8.2"
    },
    captainAmericaTheFirstAvenger : {
        title:"Captain America: The First Avenger",
        year:"2011",
        released:"22 Jul 2011",
        runtime:"124 min",
        genre:"Action, Adventure, Sci-Fi",
        director:"Joe Johnston",
        writer:"Christopher Markus, Stephen McFeely, Joe Simon",
        actors:"Chris Evans, Hugo Weaving, Samuel L. Jackson, Sebastian Stan",
        plot:"Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a \"Super-Soldier serum\". But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.",
        language:"English, Norwegian, French",
        country:"United States",
        poster:"https://m.media-amazon.com/images/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_SX300.jpg",
        rating:"6.9"
    },
    madMaxFuryRoad : {
        title:"Mad Max: Fury Road",
        year:"2015",
        released:"15 May 2015",
        runtime:"120 min",
        genre:"Action, Adventure, Sci-Fi",
        director:"George Miller",
        writer:"George Miller, Brendan McCarthy, Nick Lathouris",
        actors:"Tom Hardy, Charlize Theron, Nicholas Hoult",
        plot:"In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
        language:"English, Russian",
        country:"Australia, United States",
        poster:"https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        rating:"8.1"
    },
    noCountryForOldMen : {
        title:"No Country for Old Men",
        year:"2007",
        released:"21 Nov 2007",
        runtime:"122 min",
        genre:"Crime, Drama, Thriller",
        director:"Ethan Coen, Joel Coen",
        writer:"Joel Coen (screenplay), Ethan Coen (screenplay), Cormac McCarthy (novel)",
        actors:"Tommy Lee Jones, Javier Bardem, Josh Brolin, Woody Harrelson",
        plot:"Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
        language:"English, Spanish",
        country:"USA",
        poster:"https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
        rating:"8.1"
    },
    swades : {
        title:"Swades: We, the People",
        year:"2004",
        released:"17 Dec 2004",
        runtime:"189 min",
        genre:"Drama",
        director:"Ashutosh Gowariker",
        writer:"M.G. Sathya, Ashutosh Gowariker, Sameer Sharma",
        actors:"Shah Rukh Khan, Gayatri Joshi, Kishori Ballal",
        plot:"A successful Indian scientist returns to an Indian village to take his nanny to America with him and in the process rediscovers his roots.",
        language:"Hindi, English",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BYzExOTcwNjYtZTljMC00YTQ2LWI2YjYtNWFlYzQ0YTJhNzJmXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
        rating:"8.2"
    },
    tanhajiTheUnsungWarrior : {
        title:"Tanhaji: The Unsung Warrior",
        year:"2020",
        released:"10 Jan 2020",
        runtime:"135 min",
        genre:"Action,Biography, Drama, History",
        director:"Om Raut",
        writer:"Prakash Kapadia (story), Om Raut (story), Prakash Kapadia (screenplay), Om Raut (screenplay), Prakash Kapadia (dialogue)",
        actors:"Ajay Devgn, Saif Ali Khan, Sharad Kelkar, Kajol",
        plot:"Tanhaji Malusare, a military chieftain in the army of the Maratha king Shivaji, leads the charge to capture the strategically important Kondhana fort guarded by the army of the fierce Rajput chieftain Udaybhan Rathod.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BMDc5ZmQ3MzUtYTY4OS00YTE3LTkwNmItNmQ2ODIwNWM3MzY1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"7.6"
    },
    lagaan : {
        title:"Lagaan: Once Upon a Time in India",
        year:"2001",
        released:"15 Jun 2001",
        runtime:"224 min",
        genre:"Drama, Musical, Sport",
        director:"Ashutosh Gowariker",
        writer:"Ashutosh Gowariker, Kumar Dave, Sanjay Dayma",
        actors:"Aamir Khan, Raghuvir Yadav, Gracy Singh",
        plot:"The people of a small village in Victorian India stake their future on a game of cricket against their ruthless British rulers.",
        language:"Hindi, English",
        country:"India, United Kingdom",
        poster:"https://m.media-amazon.com/images/M/MV5BNDYxNWUzZmYtOGQxMC00MTdkLTkxOTctYzkyOGIwNWQxZjhmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        rating:"8.1"
    },
    khudaHaafiz : {
        title:"Khuda Haafiz",
        year:"2020",
        released:"14 Aug 2020",
        runtime:"133 min",
        genre:"Action, Adventure, Drama",
        director:"Faruk Kabir",
        writer:"Faruk Kabir",
        actors:"Vidyut Jammwal, Shivaleeka Oberoi, Annu Kapoor, Aahana Kumra",
        plot:"A newly married couple's life falls in jeopardy when the wife goes missing under mysterious circumstances.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BYWJhOGU2OWItMDAxMS00MzQ5LThhNjgtZTkxNjk4ZDJlOGNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"7.4"
    },
    article15 : {
        title:"Article 15",
        year:"2019",
        released:"28 Jun 2019",
        runtime:"130 min",
        genre:"Crime, Drama, Mystery",
        director:"Anubhav Sinha",
        writer:"Anubhav Sinha, Gaurav Solanki",
        actors:"Ayushmann Khurrana, Isha Talwar, Manoj Pahwa, Mohammad Zeeshan Ayyub",
        plot:"In the rural heartlands of India, an upright police officer sets out on a crusade against violent caste-based crimes and discrimination.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BZTI2NTFiMDMtZjQxNS00YjBkLWFhNWMtOTIyMzE5Yjc0ZTZiXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"8.2"
    },
    airlift : {
        title:"Airlift",
        year:"2016",
        rated:"Not Rated",
        released:"22 Jan 2016",
        runtime:"130 min",
        genre:"Drama, History",
        director:"Raja Menon",
        writer:"Raja Menon (story), Sonu Sinha (screenplay), Ritesh Shah (screenplay), Raja Menon (screenplay), Rahul Nangia (screenplay), Ritesh Shah (dialogue)",
        actors:"Akshay Kumar, Nimrat Kaur, Kumud Mishra, Prakash Belawadi, Inaam-ul-Haq",
        plot:"When Iraq invades Kuwait in August 1990, a callous Indian businessman becomes the spokesperson for more than 170,000 stranded countrymen.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BMGE1ZTkyOTMtMTdiZS00YzI2LTlmYWQtOTE5YWY0NWVlNjlmXkEyXkFqcGdeQXVyNjQ3ODkxMjE@._V1_SX300.jpg",
        rating:"8.0"
    },
    fukrey : {
        title:"Fukrey",
        year:"2013",
        released:"14 Jun 2013",
        runtime:"139 min",
        genre:"Comedy, Drama, Romance",
        director:"Mrighdeep Lamba",
        writer:"Mrighdeep Lamba, Vipul Vig",
        actors:"Pulkit Samrat, Manjot Singh, Ali Fazal, Varun Sharma",
        plot:"The paths of four dream-chasing college friends cross with an array of colourful characters, from a tough-talking Punjabi female don to a Jugaad Baaz college watchman. Mayhem ensues.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BODI5MzQ2NDg0MV5BMl5BanBnXkFtZTcwNTEwMzI1OQ@@._V1_SX300.jpg",
        rating:"6.9"
    },
    newton : {
        title:"Newton",
        year:"2017",
        released:"22 Sep 2017",
        runtime:"106 min",
        genre:"Comedy, Drama",
        director:"Amit Masurkar",
        writer:"Amit Masurkar, Mayank Tewari",
        actors:"Rajkummar Rao, Pankaj Tripathi, Anjali Patil",
        plot:"A government clerk on election duty in the conflict ridden jungle of Central India tries his best to conduct free and fair voting despite the apathy of security forces and the looming fear of guerrilla attacks by communist rebels.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BMDk4Y2Q2MmUtYjE1YS00NjEwLTg0ZGYtOGJkZjUzOTllYzA0L2ltYWdlXkEyXkFqcGdeQXVyNzA0MTg0MzE@._V1_SX300.jpg",
        rating:"7.7"
    },
    chhichhore : {
        title:"Chhichhore",
        year:"2019",
        released:"06 Sep 2019",
        runtime:"143 min",
        genre:"Comedy, Drama",
        director:"Nitesh Tiwari",
        writer:"Piyush Gupta, Nikhil Mehrotra, Nitesh Tiwari",
        actors:"Sushant Singh Rajput, Shraddha Kapoor, Varun Sharma, Tahir Raj Bhasin, Prateek Babbar",
        plot:"A tragic incident forces Anirudh, a middle-aged man, to take a trip down memory lane and reminisce his college days along with his friends, who were labelled as losers.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BYjg2ZDI2YTYtN2EwYi00YWI5LTgyMWQtMWFkYmE3NmJkOGVhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"8.3"
    },
    raazi : {
        title:"Raazi",
        year:"2018",
        released:"11 May 2018",
        runtime:"138 min",
        genre:"Action, Drama, Thriller",
        director:"Meghna Gulzar",
        writer:"Harinder S. Sikka, Meghna Gulzar, Bhavani Iyer",
        actors:"Alia Bhatt, Vicky Kaushal, Jaideep Ahlawat, Rajit Kapoor",
        plot:"A Kashmiri woman agrees to marry a Pakistani army officer in order to spy on Pakistan during the Indo-Pakistan War of 1971.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BZmVhN2JlYjEtZWFkOS00YzE0LThiNDMtMGI3NDA1MTk2ZDQ2XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"7.8"
    },

    andhadhun : {
        title:"Andhadhun",
        year:"2018",
        rated:"Not Rated",
        released:"05 Oct 2018",
        runtime:"139 min",
        genre:"Crime, Drama, Music",
        director:"Sriram Raghavan",
        writer:"Arijit Biswas, Yogesh Chandekar, Sriram Raghavan",
        actors:"Ayushmann Khurrana, Tabu, Radhika Apte, Manav Vij",
        plot:"A series of mysterious events change the life of a blind pianist, who must now report a crime that he should technically know nothing of.",
        language:"Hindi, English",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BZWZhMjhhZmYtOTIzOC00MGYzLWI1OGYtM2ZkN2IxNTI4ZWI3XkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_SX300.jpg",
        rating:"8.2"
    },
    lailaMajnu : {
        title:"Laila Majnu",
        year:"2018",
        released:"07 Sep 2018",
        runtime:"140 min",
        genre:"Drama, Romance",
        director:"Sajid Ali",
        writer:"Imtiaz Ali, Sajid Ali",
        actors:"Avinash Tiwary, Tripti Dimri, Sumit Kaul, Parmeet Sethi",
        plot:"Taking the leap out of the classic folklore, the story is set in today's time in Kashmir where Laila Majnu have problems relevant to the youth of today. While dealing with their feuding families a passionate love story unravels.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BZWZjODA1MmUtYmU0My00M2JiLTk2ODEtYzMxODJmMTM5MzY1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"7.7"
    },
    thappad : {
        title:"Thappad",
        year:"2020",
        released:"28 Feb 2020",
        runtime:"142 min",
        genre:"Drama",
        director:"Anubhav Sinha",
        writer:"Mrunmayee Lagoo, Anubhav Sinha",
        actors:"Taapsee Pannu, Pavail Gulati, Kumud Mishra, Manav Kaul",
        plot:"Thappad is a story of Amrita whose seemingly perfect life is shattered when her husband slaps her once in a party. But is one slap enough to question what a relationship stands for?",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BNWQ1Yzc2NDYtN2RjNC00ZGIyLWJkMjItMDlkODVhNjg0OTczXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"6.8"
    },
    karwaan : {
        title:"Karwaan",
        year:"2018",
        released:"03 Aug 2018",
        runtime:"114 min",
        genre:"Adventure, Comedy, Drama",
        director:"Akarsh Khurana",
        writer:"Bejoy Nambiar, Akarsh Khurana, Adhir Bhat",
        actors:"Irrfan Khan, Dulquer Salmaan, Mithila Palkar",
        plot:"Two friends and a chirpy teenager take a road trip from Bangalore to Kochi.",
        language:"Hindi, Malayalam",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BYjYxZjc1YmMtNTIyOS00OGUyLWI5MTYtOWZiNzc5Yzc4MDBhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        rating:"7.6"
    },
    detectiveByomkeshBakshy : {
        title:"Detective Byomkesh Bakshy",
        year:"2015",
        released:"03 Apr 2015",
        runtime:"139 min",
        genre:"Action, Crime, Drama",
        director:"Dibakar Banerjee",
        writer:"Urmi Juvekar, Dibakar Banerjee, Saradindu Bandopadhyay",
        actors:"Sushant Singh Rajput, Anand Tiwari, Neeraj Kabi",
        plot:"While investigating the disappearance of a chemist, a detective uncovers a larger conspiracy to unsettle Calcutta.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BMjE2MDgyOTgzN15BMl5BanBnXkFtZTgwNzY2NTYyNTM@._V1_SX300.jpg",
        rating:"7.7"
    },
    classOf83 : {
        title:"Class of 83",
        year:"2020",
        released:"21 Aug 2020",
        runtime:"98 min",
        genre:"Action, Crime, Drama",
        director:"Atul Sabharwal",
        writer:"Abhijeet Shirish Deshpande, Atul Sabharwal",
        actors:"Bobby Deol,Hitesh Bhojraj, Bhupendra Jadawat, Anup Soni, Joy Sengupta",
        plot:"The story of an upright policeman-turned-trainer whose wards deal with various complexities.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BNjU2MzAyZWEtYjMxOS00ZGExLWIxZjgtNjY2ZWJmZWQzNWM4XkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_SX300.jpg",
        rating:"5.8"
    },
    raatAkeliHai : {
        title:"Raat Akeli Hai",
        year:"2020",
        rated:"TV-MA",
        released:"31 Jul 2020",
        runtime:"149 min",
        genre:"Crime, Drama, Mystery, Thriller",
        director:"Honey Trehan",
        writer:"Smita Singh (screenplay,dialogue,story)",
        actors : "Nawazuddin Siddiqui, Radhika Apte, Aditya Srivastav, Shreedhar Dubey",
        plot : "The film follows a small town cop who is summoned to investigate the death of a politician which gets complicated by the victim's secretive family and his own conflicted heart.",
        language : "Hindi",
        country : "India",
        awards : "1 nomination.",
        poster : "https://m.media-amazon.com/images/M/MV5BYTAyYjk3ZGItYjAzMC00MjYyLTgyMzgtMDE4MTBhZTIwYTBjXkEyXkFqcGdeQXVyMTE4MzIxNTMz._V1_SX300.jpg",
        rating : "7.3"
    },
    sir : {
        title:"Sir",
        year:"2018",
        released:"13 Nov 2020",
        runtime:"99 min",
        genre:"Drama, Romance",
        director:"Rohena Gera",
        writer:"Rohena Gera",
        actors:"Tillotama Shome, Vivek Gomber, Geetanjali Kulkarni, Rahul Vohra",
        plot:"A prosperous young Indian man falls in love with his servant, a widow with the dream of becoming a fashion designer.",
        language:"Hindi, English, Marathi",
        country:"India, France",
        poster:"https://m.media-amazon.com/images/M/MV5BN2ZhMTI3MDctYTlhYy00NjBlLWEyOGEtYzE3MjM4MWFkNmQwXkEyXkFqcGdeQXVyNTA3NTQ4OTg@._V1_SX300.jpg",
        rating:"7.7"
    },
    uri : {
        title:"Uri: The Surgical Strike",
        year:"2018",
        released:"11 Jan 2019",
        runtime:"138 min",
        genre:"Action, Drama, War",
        director:"Aditya Dhar",
        writer:"Aditya Dhar",
        actors:"Vicky Kaushal, Paresh Rawal, Mohit Raina, Kirti Kulhari",
        plot:"Indian army special forces execute a covert operation, avenging the killing of fellow army men at their base by a terrorist group.",
        language:"Hindi",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BMWU4ZjNlNTQtOGE2MS00NDI0LWFlYjMtMmY3ZWVkMjJkNGRmXkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_SX300.jpg",
        rating:"8.2"
    },
    tumbbad : {
        title:"Tumbbad",
        year:"2018",
        released:"12 Oct 2018",
        runtime:"104 min",
        genre:"Drama, Fantasy, Horror",
        director:"Rahi Anil Barve, Anand Gandhi, Adesh Prasad",
        writer:"Mitesh Shah, Adesh Prasad, Rahi Anil Barve",
        actors:"Sohum Shah, Jyoti Malshe, Anita Date",
        plot:"A mythological story about a goddess who created the entire universe. The plot revolves around the consequences when humans build a temple for her first-born.",
        language:"Hindi",
        country:"India, Sweden",
        poster:"https://m.media-amazon.com/images/M/MV5BYmQxNmU4ZjgtYzE5Mi00ZDlhLTlhOTctMzJkNjk2ZGUyZGEwXkEyXkFqcGdeQXVyMzgxMDA0Nzk@._V1_SX300.jpg",
        rating:"8.3"
    },
    gullyBoy : {
        title:"Gully Boy",
        year:"2019",
        released:"14 Feb 2019",
        runtime:"154 min",
        genre:"Drama, Music, Romance",
        director:"Zoya Akhtar",
        writer:"Zoya Akhtar, Reema Kagti, Vijay Maurya",
        actors:"Ranveer Singh, Vijay Varma, Siddhant Chaturvedi, Alia Bhatt",
        plot:"A coming-of-age story based on the lives of street rappers in Mumbai.",
        language:"Hindi, English",
        country:"India",
        poster:"https://m.media-amazon.com/images/M/MV5BZDkzMTQ1YTMtMWY4Ny00MzExLTkzYzEtNzZhOTczNzU2NTU1XkEyXkFqcGdeQXVyODY3NjMyMDU@._V1_SX300.jpg",
        rating:"8.0"
    }
};

module.exports = moviesDB;

